// Generated by OmO. Delete this file to stop loading the default global extension.
export { default } from "file:///home/arachalouski/.bun/install/global/node_modules/@code-yeongyu/senpi/dist/core/extensions/builtin/tps.js";
